[env:esp32dev]
platform = espressif32@6.13.0
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
  mobizt/Firebase Arduino Client Library for ESP8266 and ESP32@4.4.17
  adafruit/DHT sensor library@1.4.7
  adafruit/Adafruit Unified Sensor@1.1.15
  https://github.com/mandulaj/PZEM-004T-v30.git#v1.2.1
